### ISSUE TITLE
Column sizes are only respected for lowercase column names when using user profile

### ISSUE THREAD

**Issue by cezarmoise** [scylladb/cassandra-stress#46]
It seems like column names in the user profile are transformed to lowercase when created, but when written the are used in a case sensitive way, so the options defined in columnspec are ignored, and the defaults are applied.

### Example using `write`
This command
```
cassandra-stress write cl=QUORUM n=200000 -schema replication(strategy=NetworkTopologyStrategy,replication_factor=3) -col size=fixed(20) n=FIXED(8) -pop dist=UNIFORM(1..1000000000) -node 127.0.56.1,127.0.56.2,127.0.56.3
```
results in data like this
| Column   | Value                                                                      |   Length |
|----------|----------------------------------------------------------------------------|----------|
| key      | b'KN9O9M2N31'                                                              |       10 |
| C0       | b'h\xbc\x89\xe8X\xd8\x0exrI(e\x07w\xae>\x1dt2x'                            |       20 |
| C1       | b'\xb4\x83\xd1\xa3\xfc\x99\x07MJ!^\xc8\xea\xd0\xacZ\x99\x8e\x04\xb6'       |       20 |
| C2       | b'\x90\x98\xe6\xee\xbd\xd9\xecq+\x0c\x1d\xd7\xb7\x17\xf6\xabV\xdf\x91\x95' |       20 |
| C3       | b'\xe5NW\x16.\x8b!\x1f\x12DDp\xe2\xe6\xbcf\xbdA3\x05'                      |       20 |
| C4       | b'\x04\xae\xaf\x02\xe89\xe4\x13oI\xa5H\x15\x03\xe7\x8c\xaa\xeeWz'          |       20 |
| C5       | b'T\x9bA\xc8lb\xb0)u\xe3\xa6\x9a\x12\xe7\xdd\\\x8ah\xc6C'                  |       20 |
| C6       | b'5\x99\x02\x9d{\xcc\xd5>\x86]\r\xad\xea\x1b\x01x\xda\xf1\xc36'            |       20 |
| C7       | b'\x07\xc1<\xbc\x9dfL\xf2B\x84\x8d\xb1\x80h\xd8( -\xf4\x89'                |       20 |

Note that the column names are uppercase

### Example using `user profile` same column names
This command
```
running command: cassandra-stress user profile=/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/test_data/c-s-profiles/reproducer_uppercase.yaml ops(insert=1) cl=QUORUM n=200000 -pop dist=UNIFORM(1..1000000000) -node 127.0.13.1,127.0.13.2,127.0.13.3
```
with this config
```yaml
keyspace: keyspace1

keyspace_definition: |
  CREATE KEYSPACE keyspace1 WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3};

table: standard1

table_definition: |
  CREATE TABLE standard1 (
    key blob PRIMARY KEY,
    C0 blob,
    C1 blob,
    C2 blob,
    C3 blob,
    C4 blob,
    C5 blob,
    C6 blob,
    C7 blob
  );

columnspec:
  - name: key
    size: fixed(10)
  - name: C0
    size: fixed(20)
  - name: C1
    size: fixed(20)
  - name: C2
    size: fixed(20)
  - name: C3
    size: fixed(20)
  - name: C4
    size: fixed(20)
  - name: C5
    size: fixed(20)
  - name: C6
    size: fixed(20)
  - name: C7
    size: fixed(20)

insert:
  partitions: fixed(1)
  select:     fixed(1)/1
  batchtype:  UNLOGGED

queries:
  single:
    cql: select * from standard1 where key = ? LIMIT 1
    fields: samerow
```

results in data like
| Column   | Value                               |   Length |
|----------|-------------------------------------|----------|
| key      | b'`\x82\xeeHK\xe7\xd8\xc6\xb1\xa3'  |       10 |
| c0       | b'\x01\xca\x0c\x96^\xa7'            |        6 |
| c1       | b'i\xeb;\x871\x9a'                  |        6 |
| c2       | b'5\xf3\x18?'                       |        4 |
| c3       | b'\xa7\x9c\xee\xdamJ\x9b\t'         |        8 |
| c4       | b'\xb8\x0f\x80\xd6\xb0\xf5\x87\x9d' |        8 |
| c5       | b'\x8cw\xe7L\xe7r'                  |        6 |
| c6       | b'\x94\xf1\xd7*\xd2\xbd\x14'        |        7 |
| c7       | b',\xf9\xef\xeb\x1e\xac\xcb'        |        7 |

Note that the column names are now all lowercase

### Example using `user profile` lowecase column names
This command
```
running command: cassandra-stress user profile=/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/test_data/c-s-profiles/reproducer_uppercase.yaml ops(insert=1) cl=QUORUM n=200000 -pop dist=UNIFORM(1..1000000000) -node 127.0.13.1,127.0.13.2,127.0.13.3
```
with this config
```yaml
keyspace: keyspace1

keyspace_definition: |
  CREATE KEYSPACE keyspace1 WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3};

table: standard1

table_definition: |
  CREATE TABLE standard1 (
    key blob PRIMARY KEY,
    c0 blob,
    c1 blob,
    c2 blob,
    c3 blob,
    c4 blob,
    c5 blob,
    c6 blob,
    c7 blob
  );

columnspec:
  - name: key
    size: fixed(10)
  - name: c0
    size: fixed(20)
  - name: c1
    size: fixed(20)
  - name: c2
    size: fixed(20)
  - name: c3
    size: fixed(20)
  - name: c4
    size: fixed(20)
  - name: c5
    size: fixed(20)
  - name: c6
    size: fixed(20)
  - name: c7
    size: fixed(20)

insert:
  partitions: fixed(1)
  select:     fixed(1)/1
  batchtype:  UNLOGGED

queries:
  single:
    cql: select * from standard1 where key = ? LIMIT 1
    fields: samerow

```
results in data like

| Column   | Value                                                                      |   Length |
|----------|----------------------------------------------------------------------------|----------|
| key      | b'\xdam\xefC\xd2\xee}2=\xc0'                                               |       10 |
| c0       | b'l\xcf\xec\xc9\xc0w\x10\x01\xba\xa5\x1b\xd9\xde\x9aD\xc0\x95\x14\x8d\x90' |       20 |
| c1       | b'\xc7\xeb\xaa`\xe0\x0b\xc2\xf4*"\xe29\x9a\xd9\xd0\x01\xa1\xc7\x1d\x83'    |       20 |
| c2       | b'\x9d9;\x8d\xe9\xd1\xebofw\xa5\xa7\xb9\xa5\xc8\xfaC\x182\x98'             |       20 |
| c3       | b'wK\xd5\xf3\xf0\xce\x13\x92.\x02-\xb7\xb5\xa2<U\xad\xb4\xbfi'             |       20 |
| c4       | b'\xcd\xd7v\xcb".\x06\xd48?\xc3-g\x0e\xc5\x84P}\xd3\xbb'                   |       20 |
| c5       | b'$Z\xae\x0b\xb3a\x1fx\xa8\x03\xc6\xf9R\xa7\x00\xe8\x84y\x80\xcb'          |       20 |
| c6       | b'\x1dI\x15Lyv\x15c\xd1&$X\x02\x0f\x06\xd5\xd4\x80\x18?'                   |       20 |
| c7       | b' \xd1WmM\xfch\x9cK\xb2D\x16\x9a\xd6\r\\\x11\x16DA'                       |       20 |

### Example using different column name
```
cassandra-stress user profile=/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/test_data/c-s-profiles/reproducer_variants.yaml ops(insert=1) cl=QUORUM n=200000 -pop dist=UNIFORM(1..1000000000) -node 127.0.92.1,127.0.92.2,127.0.92.3

```

this is the config 
```yaml
keyspace: keyspace1

keyspace_definition: |
  CREATE KEYSPACE keyspace1 WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3};

table: standard1

table_definition: |
  CREATE TABLE standard1 (
    key blob PRIMARY KEY,
    C0 blob,
    c1 blob,
    lowercase blob,
    lowercase1 blob,
    UPPERCASE blob,
    UPPERCASE1 blob,
    Capitalized blob,
    Capitalized1 blob,
    mIxEdTeXt blob,
    MiXeDcAsE blob
  );

columnspec:
  - name: key
    size: fixed(10)
  - name: C0
    size: fixed(20)
  - name: c1
    size: fixed(20)
  - name: lowercase
    size: fixed(20)
  - name: lowercase1
    size: fixed(20)
  - name: UPPERCASE
    size: fixed(20)
  - name: UPPERCASE1
    size: fixed(20)
  - name: Capitalized
    size: fixed(20)
  - name: Capitalized1
    size: fixed(20)
  - name: mIxEdTeXt
    size: fixed(20)
  - name: MiXeDcAsE
    size: fixed(20)

insert:
  partitions: fixed(1)
  select:     fixed(1)/1
  batchtype:  UNLOGGED

queries:
  single:
    cql: select * from standard1 where key = ? LIMIT 1
    fields: samerow

```

results in data like

| Column       | Value                                                                   |   Length |
|--------------|-------------------------------------------------------------------------|----------|
| key          | b'HhQ\x92\x18\xd3.\x98\xa6\xbb'                                         |       10 |
| c0           | b'\xb6\xbc\x06\xe6\x99j\xa8\x14'                                        |        8 |
| c1           | b'\xb7\xdf\x0c\xe1\xa9\r\xb3\xf4\x9afI\x08\xea\xc6\xc5X6c\t\x9e'        |       20 |
| capitalized  | b'\xfb.H\x8f\xf0'                                                       |        5 |
| capitalized1 | b'\x99Y\x95$j'                                                          |        5 |
| lowercase    | b'\x90\xd1\xda\xe9l\xec\xd9q\xae:\x8f\x89\xa2\xc9\xbf\xc0\xa4B\xfa\xd9' |       20 |
| lowercase1   | b'\xeb\xf5V\x1bB\xc7\x8f\xf9\x9er\xc4\x9a1r\r\xe3:`\x0e\xfd'            |       20 |
| mixedcase    | b'Z\xa0S\xd0\xf6\xcc\xae!'                                              |        8 |
| mixedtext    | b'\x0cW\xd3\x04\xaa\xa6\x97'                                            |        7 |
| uppercase    | b"\xcaO'h"                                                              |        4 |
| uppercase1   | b'\x07w\xd6\xbd\x1a\xbd'                                                |        6 |

Note that the column names are now all lowercase
Only the ones that were initially lowercase are the correct length

Migrated to Jira: [QATOOLS-22](https://scylladb.atlassian.net/browse/QATOOLS-22)

[QATOOLS-22]: https://scylladb.atlassian.net/browse/QATOOLS-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
